model:
  cldm:
    target: diffbir.model.cldm_4channel.ControlLDM4Channel
    params:
      latent_scale_factor: 0.18215
      unet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
      vae_cfg:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 4  # Changed from 3 to 4 for RGB+mono
          out_ch: 3       # Output RGB only
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      clip_cfg:
        embed_dim: 1024
        vision_cfg:
          image_size: 224
          layers: 32
          width: 1280
          head_width: 80
          patch_size: 14
        text_cfg:
          context_length: 77
          vocab_size: 49408
          width: 1024
          heads: 16
          layers: 24
        layer: "penultimate"
      controlnet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 4  # Changed from 4 to 4 for RGB+mono condition
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

  swinir:
    target: diffbir.model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 4  # Changed from 3 to 4 for RGB+mono input
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8

  diffusion:
    target: diffbir.model.gaussian_diffusion.Diffusion
    params:
      linear_start: 0.00085
      linear_end: 0.0120
      timesteps: 1000
      zero_snr: False
      parameterization: eps

dataset:
  train:
    target: diffbir.dataset.huggingface_rgbmono.HuggingFaceRGBMonoDataset
    params:
      # Paths will be read from dataset_config.py - no need to set here
      split: "train"
      out_size: 512
      crop_type: center
      use_hflip: True
      use_rot: True
      p_empty_prompt: 0.5
      debug_logging: True

batch_transform:
  target: diffbir.dataset.batch_transform.IdentityBatchTransform

train:
  # pretrained sd v2.1 path - REQUIRED: Set this to your SD v2.1 checkpoint path
  sd_path: "weights/v2-1_512-ema-pruned.ckpt"
  # experiment directory path - REQUIRED: Set this to your experiment directory
  exp_dir: "experiments/4channel_rgbmono"
  # stage 1 swinir path - REQUIRED: Set this to your SwinIR checkpoint path
  # For now, we'll need to train a 4-channel SwinIR or modify an existing one
  swinir_path: "weights/swinir_4channel.pth"
  learning_rate: 1e-4
  batch_size: 8  # Smaller batch size for 4-channel processing
  num_workers: 4
  train_steps: 30000
  log_every: 50
  ckpt_every: 5000
  image_every: 1000
  resume: ~
  noise_aug_timestep: 0